from flask import Flask, request, jsonify, send_from_directory
from werkzeug.utils import secure_filename
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import os
import tensorflow as tf
import numpy as np
from flask_cors import CORS

# 1. Point Flask to serve from the "build" folder (generated by React).
app = Flask(__name__, static_folder='build', static_url_path='')
CORS(app)  # Enable CORS for all routes

class_names = [
    'actinic keratosis', 'basal cell carcinoma', 'dermatofibroma',
    'melanoma', 'nevus', 'pigmented benign keratosis',
    'seborrheic keratosis', 'squamous cell carcinoma', 'vascular lesion'
]

# Dictionary to hold models
models = {}

# 2. Load your model from "src/models"
def load_model_func(model_name, path):
    global models
    try:
        model = tf.keras.models.load_model(path)
        models[model_name] = model
        print(f"Model {model_name} loaded successfully from {path}.")
    except Exception as e:
        print(f"Failed to load model from {path}: {e}")

load_model_func("skin_cancer_model_v6_8785", 'src/models/skin_cancer_model_v6_8785.keras')
model = models["skin_cancer_model_v6_8785"]

def preprocess_image(image_path):
    img = load_img(image_path, target_size=(180, 180))
    img_array = img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    return img_array

def predict(image_path, model, class_names):
    img_array = preprocess_image(image_path)
    predictions = model.predict(img_array)
    pred_index = np.argmax(predictions[0])
    pred_class = class_names[pred_index]
    confidence = predictions[0][pred_index]
    print(f"Predictions: {predictions}")
    print(f"Predicted Class: {pred_class}")
    print(f"Confidence: {confidence:.2%}")
    return pred_class, confidence

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in {'png', 'jpg', 'jpeg', 'gif'}

# 3. Your API endpoint under "/api"
@app.route('/api/analyze-image', methods=['POST'])
def analyze_image():
    print("Received request to /api/analyze-image")
    if 'image' not in request.files:
        return jsonify({'error': 'No file part'}), 401
    file = request.files['image']
    if file.filename == '':
        return jsonify({'error': 'No selected file'}), 402
    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        uploads_dir = 'uploads'
        if not os.path.exists(uploads_dir):
            os.makedirs(uploads_dir)
            print("Created uploads directory")
        file_path = os.path.join(uploads_dir, filename)
        file.save(file_path)
        print(f"Saved file to {file_path}")
        predicted_class, confidence = predict(file_path, model, class_names)
        os.remove(file_path)  # Optionally remove the file after analysis
        return jsonify({
            'prediction': predicted_class,
            'confidence': f"{confidence:.2%}"
        })
    else:
        return jsonify({'error': 'File not allowed'}), 403

# 4. Optional test endpoint to confirm Flask is working
@app.route('/api/test')
def api_test():
    return "Flask API is running!"

# 5. Catch-all route for serving your React app
#    Any route that doesn't match "/api" endpoints will serve "index.html"
@app.route('/', defaults={'path': ''})
@app.route('/<path:path>')
def serve_react(path):
    # If a file under build/ exists (e.g. JS, CSS, images), serve it
    if path != "" and os.path.exists(os.path.join(app.static_folder, path)):
        return send_from_directory(app.static_folder, path)
    # Otherwise, serve the index.html (client-side routing)
    return send_from_directory(app.static_folder, 'index.html')

if __name__ == '__main__':
    # debug=False for production
    app.run(debug=False)
